CREATE DATABASE wiki;
CREATE USER wikiuser WITH ENCRYPTED PASSWORD 'wikipassword';
GRANT ALL PRIVILEGES ON DATABASE wiki TO wikiuser;
ALTER DATABASE wiki OWNER TO wikiuser;

CREATE DATABASE backend;
CREATE DATABASE backend-test;
CREATE USER backenduser WITH ENCRYPTED PASSWORD 'backendpassword';
GRANT ALL PRIVILEGES ON DATABASE backend TO backenduser;
GRANT ALL PRIVILEGES ON DATABASE backend-test TO backenduser;
ALTER DATABASE backend OWNER TO backenduser;
